import React, { Component } from 'react';
import { Section, Content } from '../components/Content';
import { Wrapper } from '../components/Wrapper';

class Dashboard extends Component {
    render() {
        return (
            <Wrapper className='dashboard' id='dashboard'>
                {/* Dashboard - World - US - Local Awareness Section */ }
                <Section className='section'>
                    <Content className='content'>
                        <h3>World - US - Local Awareness</h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue nisi vitae suscipit tellus mauris a diam. Nunc scelerisque viverra mauris in aliquam sem. Proin gravida hendrerit lectus a. At imperdiet dui accumsan sit amet nulla facilisi morbi. Dolor purus non enim praesent elementum. Scelerisque varius morbi enim nunc faucibus a pellentesque. Nunc congue nisi vitae suscipit tellus. Etiam tempor orci eu lobortis elementum. Sed libero enim sed faucibus turpis in eu mi bibendum. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque.

Sed risus pretium quam vulputate dignissim. Varius morbi enim nunc faucibus a pellentesque sit. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Nunc consequat interdum varius sit amet mattis. Nascetur ridiculus mus mauris vitae ultricies leo integer. Lorem ipsum dolor sit amet. Dui sapien eget mi proin sed libero enim. At imperdiet dui accumsan sit amet. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Quisque egestas diam in arcu cursus euismod quis viverra. Auctor eu augue ut lectus. In aliquam sem fringilla ut morbi tincidunt.

Tincidunt eget nullam non nisi est sit amet facilisis. Risus nec feugiat in fermentum posuere. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Est sit amet facilisis magna etiam tempor orci. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Varius vel pharetra vel turpis nunc eget lorem dolor. Pellentesque id nibh tortor id aliquet lectus. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Sed augue lacus viverra vitae. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Nullam non nisi est sit. Ridiculus mus mauris vitae ultricies leo integer. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate.

Nulla pharetra diam sit amet nisl suscipit. Dictumst quisque sagittis purus sit amet volutpat consequat. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Eget arcu dictum varius duis at. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Ac turpis egestas sed tempus urna et pharetra. At varius vel pharetra vel turpis nunc eget lorem. Augue eget arcu dictum varius duis at consectetur lorem. Odio morbi quis commodo odio aenean sed adipiscing diam donec. Interdum consectetur libero id faucibus nisl tincidunt eget. Lacus luctus accumsan tortor posuere ac ut consequat semper. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Non enim praesent elementum facilisis leo vel fringilla est. Malesuada fames ac turpis egestas sed. Sollicitudin tempor id eu nisl nunc mi. Tempus quam pellentesque nec nam aliquam sem. Et tortor consequat id porta nibh venenatis cras sed. Augue neque gravida in fermentum. Tellus integer feugiat scelerisque varius morbi enim. Nulla malesuada pellentesque elit eget gravida cum sociis.

Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Varius quam quisque id diam. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Tempor nec feugiat nisl pretium fusce id velit ut. Eu non diam phasellus vestibulum. At ultrices mi tempus imperdiet. Ipsum a arcu cursus vitae congue mauris. Sed velit dignissim sodales ut eu sem integer vitae justo. Elementum pulvinar etiam non quam lacus suspendisse. Vitae congue mauris rhoncus aenean vel elit. Consequat mauris nunc congue nisi vitae. Nulla pellentesque dignissim enim sit amet venenatis urna. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula.
                    </Content>
                </Section>

                {/* Dashboard - Personal Inventory Section */ }
                <Section className='section'>
                    <Content className='content'>
                        <h3>Personal Inventory Section</h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue nisi vitae suscipit tellus mauris a diam. Nunc scelerisque viverra mauris in aliquam sem. Proin gravida hendrerit lectus a. At imperdiet dui accumsan sit amet nulla facilisi morbi. Dolor purus non enim praesent elementum. Scelerisque varius morbi enim nunc faucibus a pellentesque. Nunc congue nisi vitae suscipit tellus. Etiam tempor orci eu lobortis elementum. Sed libero enim sed faucibus turpis in eu mi bibendum. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque.

    Sed risus pretium quam vulputate dignissim. Varius morbi enim nunc faucibus a pellentesque sit. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Nunc consequat interdum varius sit amet mattis. Nascetur ridiculus mus mauris vitae ultricies leo integer. Lorem ipsum dolor sit amet. Dui sapien eget mi proin sed libero enim. At imperdiet dui accumsan sit amet. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Quisque egestas diam in arcu cursus euismod quis viverra. Auctor eu augue ut lectus. In aliquam sem fringilla ut morbi tincidunt.

    Tincidunt eget nullam non nisi est sit amet facilisis. Risus nec feugiat in fermentum posuere. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Est sit amet facilisis magna etiam tempor orci. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Varius vel pharetra vel turpis nunc eget lorem dolor. Pellentesque id nibh tortor id aliquet lectus. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Sed augue lacus viverra vitae. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Nullam non nisi est sit. Ridiculus mus mauris vitae ultricies leo integer. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate.

    Nulla pharetra diam sit amet nisl suscipit. Dictumst quisque sagittis purus sit amet volutpat consequat. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Eget arcu dictum varius duis at. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Ac turpis egestas sed tempus urna et pharetra. At varius vel pharetra vel turpis nunc eget lorem. Augue eget arcu dictum varius duis at consectetur lorem. Odio morbi quis commodo odio aenean sed adipiscing diam donec. Interdum consectetur libero id faucibus nisl tincidunt eget. Lacus luctus accumsan tortor posuere ac ut consequat semper. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Non enim praesent elementum facilisis leo vel fringilla est. Malesuada fames ac turpis egestas sed. Sollicitudin tempor id eu nisl nunc mi. Tempus quam pellentesque nec nam aliquam sem. Et tortor consequat id porta nibh venenatis cras sed. Augue neque gravida in fermentum. Tellus integer feugiat scelerisque varius morbi enim. Nulla malesuada pellentesque elit eget gravida cum sociis.

    Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Varius quam quisque id diam. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Tempor nec feugiat nisl pretium fusce id velit ut. Eu non diam phasellus vestibulum. At ultrices mi tempus imperdiet. Ipsum a arcu cursus vitae congue mauris. Sed velit dignissim sodales ut eu sem integer vitae justo. Elementum pulvinar etiam non quam lacus suspendisse. Vitae congue mauris rhoncus aenean vel elit. Consequat mauris nunc congue nisi vitae. Nulla pellentesque dignissim enim sit amet venenatis urna. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula.
                    </Content>
                </Section>

                {/* Dashboard - Food Donation Information Section */ }
                <Section className='section'>
                    <Content className='content'>
                        <h3>Food Donation Information Section</h3>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue nisi vitae suscipit tellus mauris a diam. Nunc scelerisque viverra mauris in aliquam sem. Proin gravida hendrerit lectus a. At imperdiet dui accumsan sit amet nulla facilisi morbi. Dolor purus non enim praesent elementum. Scelerisque varius morbi enim nunc faucibus a pellentesque. Nunc congue nisi vitae suscipit tellus. Etiam tempor orci eu lobortis elementum. Sed libero enim sed faucibus turpis in eu mi bibendum. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque.

Sed risus pretium quam vulputate dignissim. Varius morbi enim nunc faucibus a pellentesque sit. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Nunc consequat interdum varius sit amet mattis. Nascetur ridiculus mus mauris vitae ultricies leo integer. Lorem ipsum dolor sit amet. Dui sapien eget mi proin sed libero enim. At imperdiet dui accumsan sit amet. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Quisque egestas diam in arcu cursus euismod quis viverra. Auctor eu augue ut lectus. In aliquam sem fringilla ut morbi tincidunt.

Tincidunt eget nullam non nisi est sit amet facilisis. Risus nec feugiat in fermentum posuere. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Est sit amet facilisis magna etiam tempor orci. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Varius vel pharetra vel turpis nunc eget lorem dolor. Pellentesque id nibh tortor id aliquet lectus. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Sed augue lacus viverra vitae. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Nullam non nisi est sit. Ridiculus mus mauris vitae ultricies leo integer. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate.

Nulla pharetra diam sit amet nisl suscipit. Dictumst quisque sagittis purus sit amet volutpat consequat. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Eget arcu dictum varius duis at. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Ac turpis egestas sed tempus urna et pharetra. At varius vel pharetra vel turpis nunc eget lorem. Augue eget arcu dictum varius duis at consectetur lorem. Odio morbi quis commodo odio aenean sed adipiscing diam donec. Interdum consectetur libero id faucibus nisl tincidunt eget. Lacus luctus accumsan tortor posuere ac ut consequat semper. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Non enim praesent elementum facilisis leo vel fringilla est. Malesuada fames ac turpis egestas sed. Sollicitudin tempor id eu nisl nunc mi. Tempus quam pellentesque nec nam aliquam sem. Et tortor consequat id porta nibh venenatis cras sed. Augue neque gravida in fermentum. Tellus integer feugiat scelerisque varius morbi enim. Nulla malesuada pellentesque elit eget gravida cum sociis.

Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Varius quam quisque id diam. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Tempor nec feugiat nisl pretium fusce id velit ut. Eu non diam phasellus vestibulum. At ultrices mi tempus imperdiet. Ipsum a arcu cursus vitae congue mauris. Sed velit dignissim sodales ut eu sem integer vitae justo. Elementum pulvinar etiam non quam lacus suspendisse. Vitae congue mauris rhoncus aenean vel elit. Consequat mauris nunc congue nisi vitae. Nulla pellentesque dignissim enim sit amet venenatis urna. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula.
                    </Content>
                </Section>

            </Wrapper>

        );
    }
}

export default Dashboard;